{% set name = "opuslib" %}
{% set version = "2.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://github.com/orion-labs/{{ name }}/archive/refs/tags/{{ version }}.tar.gz"
  sha256: 051522d44d74c1d2f6b87c77b717faffb27d6315814ec1bbfefeab950456018e

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - libopus

test:
  imports:
    - opuslib
    - opuslib.api
  requires:
    - coverage >=4.4.1
    - nose >=1.3.7
    

about:
  home: "https://github.com/orion-labs/opuslib"
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE 
  summary: "Python bindings to the libopus, IETF low-delay audio codec"
  doc_url: https://github.com/orion-labs/opuslib 
  dev_url: https://github.com/orion-labs/opuslib

extra:
  recipe-maintainers:
    - JennaLipscomb
    - mxr-conda
